### ISSUE TITLE
Custom download location for individual accounts

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#25]
Hi!
I was hoping that you could create a database check where Raider would not download posts that were already downloaded earlier. If I move photos from an already downloaded folder, Raider re-downloads them.

**Comment by AssetKid** [comment]
The `_id` file already does this.

**Comment by KaunWho** [comment]
Is there a possibility to have these _id files in a different root folder? One folder for all id files maybe. It would be easier to move data if that can be made possible. I moved the complete folder (with the id file) and therefore it might have started to download again.

Thanks a lot for the application! It works like a charm!

**Comment by AssetKid** [comment]
It would be much easier to support downloading accounts to different locations. I have changed the title of the issue and reopened the it.

**Comment by supersick123** [comment]
> Is there a possibility to have these _id files in a different root folder? One folder for all id files maybe. It would be easier to move data if that can be made possible. I moved the complete folder (with the id file) and therefore it might have started to download again.
> 
> Thanks a lot for the application! It works like a charm!

I actually want to second this as well. I use 4K Stogram to subscribe to the posts and stories of over 5000 accounts, and >2 years' worth of content no longer fits my 10TB external hard drive Nowadays, I download content to my laptop then transfer out everything every week to a 2nd hard drive. However, I don't need to start over every time, because even if I transfer out the 5000+ folders containing "content", the program remembers where I left off because I can keep/reuse the single "database file" (.sqlite in this case) that houses all the info for 5000+ accounts. If I had to pull the _id file out of each folder, it would take forever to get everything setup again.

I know you mentioned it is harder to make a root folder, so I don't want you to feel like you're wasting your time. I'd be happy to make a donation if you think this is something that can be made possible in the near future! :) Using Raider would save me the *hours* I spend updating each account manually with 4K Stogram, and I feel this donation would be worth it in the long run.
