### ISSUE TITLE
Blinking icon when error/popup

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#48]
Is there a way to make the icon blink (like when outlook has a meeting reminder), when there's an error downloading an account. Specially when updating all the accounts, there are times when there's an issue. You dont know there's an issue if you hae Raider Minimized and working on a different application. A desktop notification is not required but just a light up/blinking of Raider's icon to indicate that there's something that needs my attention then that would help.

**Comment by denbartman** [comment]
The reason i ask this is that Raider is running on a server (without screen attached) and i always have to connect to the server if everything is still ok. So any type of monitorable event would be nice.
- Or make it possible to send a mail when this type of error occurs?
- Or create a system event. (So that it can be monitored by windows)
- Or even a writing an error message to a text file would be ok.
